version: '3'
services:
  bot:
    build: .
    container_name: queue_bot
    image: bot
    environment:
      - TOKEN=${TOKEN}
      - host=${host}
      - user=${user}
      - password=${password}
      - db_name=${db_name}
      - port=${port}
    ports:
      - "5432:5432"